version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start --optimized
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER:-facoffee}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-facoffeepass}
      KC_DB: dev-file
      KC_PROXY: edge
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      KC_HTTPS_ENABLED: false
    volumes:
      - keycloak_data:/opt/keycloak/data/
  
  financeiro_api:
    build:
      context: ./facoffee-financeiro
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      PORT: 80
      BASE_URL: /
      KEYCLOAK_URL: http://keycloak:8080/
      KEYCLOAK_REALM: ${KEYCLOAK_REALM:-facoffee}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID:-facoffee}
    volumes:
      - financeiro_data:/app/data
    links:
      - keycloak

  caddy:
    image: caddy:alpine
    command: caddy run --watch -c /etc/caddy/Caddyfile
    restart: unless-stopped
    environment:
      DOMAIN: ${DOMAIN:-localhost}
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
    depends_on:
      - keycloak
      - financeiro_api
    healthcheck:
      test: ["CMD", "caddy", "version"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  keycloak_data:
    driver: local
  financeiro_data:
    driver: local
  caddy_data:
    driver: local
